databases:
  - name: tsukureview_beta_db
    databaseName: tsukureview_beta_db
    user: tsukureview
    region: singapore
    plan: free

services:
  - type: web
    name: tsukureview_beta
    env: python
    region: singapore
    plan: free
    branch: deploy
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tsukureview_beta_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true