# Generated by Django 3.2 on 2022-09-03 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='科目番号')),
                ('name', models.CharField(max_length=150, verbose_name='科目名')),
                ('unit', models.CharField(default='', max_length=10, verbose_name='単位数')),
                ('grade', models.CharField(default='', max_length=15, verbose_name='履修年次')),
                ('semester', models.CharField(default='', max_length=15, verbose_name='学期')),
                ('teachers', models.TextField(blank=True, default='', max_length=100, verbose_name='教員名')),
                ('overview', models.TextField(blank=True, default='', max_length=200, verbose_name='概要')),
                ('subtype', models.TextField(blank=True, default='', max_length=32, verbose_name='種類')),
                ('schools', models.CharField(blank=True, default='', max_length=20, verbose_name='学群等')),
                ('colleges', models.CharField(blank=True, default='', max_length=40, verbose_name='学類等')),
                ('star1', models.IntegerField(default=0, verbose_name='星1')),
                ('star2', models.IntegerField(default=0, verbose_name='星2')),
                ('star3', models.IntegerField(default=0, verbose_name='星3')),
                ('star4', models.IntegerField(default=0, verbose_name='星4')),
                ('star5', models.IntegerField(default=0, verbose_name='星5')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='投稿者id')),
                ('sender_name', models.CharField(max_length=40, verbose_name='投稿者名')),
                ('text', models.TextField(max_length=500, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('lecture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='review.subject')),
            ],
        ),
    ]
