# Generated by Django 3.2 on 2022-09-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='科目番号')),
                ('name', models.CharField(max_length=150, verbose_name='科目名')),
                ('unit', models.CharField(default='', max_length=10, verbose_name='単位数')),
                ('grade', models.CharField(default='', max_length=15, verbose_name='履修年次')),
                ('semester', models.CharField(default='', max_length=15, verbose_name='学期')),
                ('teachers', models.TextField(blank=True, default='', max_length=100, verbose_name='教員名')),
                ('overview', models.TextField(blank=True, default='', max_length=200, verbose_name='概要')),
                ('subtype', models.TextField(blank=True, default='', max_length=32, verbose_name='種類')),
                ('schools', models.CharField(blank=True, default='', max_length=20, verbose_name='学群等')),
                ('colleges', models.CharField(blank=True, default='', max_length=40, verbose_name='学類等')),
                ('star1', models.IntegerField(default=0, verbose_name='星1')),
                ('star2', models.IntegerField(default=0, verbose_name='星2')),
                ('star3', models.IntegerField(default=0, verbose_name='星3')),
                ('star4', models.IntegerField(default=0, verbose_name='星4')),
                ('star5', models.IntegerField(default=1, verbose_name='星5')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='口コミid')),
                ('sender_name', models.CharField(max_length=40, verbose_name='投稿者名')),
                ('sender_college', models.IntegerField(choices=[(1, '人文学類'), (2, '比較文化学類'), (3, '日本語・日本文化学類'), (4, '社会学類'), (5, '国際総合学類'), (6, '教育 学類'), (7, '心理学類'), (8, '障害科学類'), (9, '生物学類'), (10, '生物資源学類'), (11, '地球学類'), (12, '数学類'), (13, '物理学類'), (14, '化学類'), (15, '応用理工学類'), (16, '工学システム学類'), (17, '社会工学類'), (18, '情報科学類'), (19, '情報メディア創成学類'), (20, '知識情報・図書館学類'), (21, '医学類'), (22, '看護学類'), (23, '医療科学類'), (24, '体育専門学群'), (25, '芸術専門学群'), (26, '総合学域群')], default=1, max_length=40, verbose_name='投稿者の所属学類')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='タイトル')),
                ('year', models.IntegerField(choices=[(2022, '2022年'), (2021, '2021年'), (2020, '2020年'), (2019, '2019年')], default=2022, verbose_name='受講した年度')),
                ('rating', models.IntegerField(choices=[(5, '5.0'), (4, '4.0'), (3, '2.0'), (2, '2.0'), (1, '1.0')], default=5, verbose_name='星')),
                ('grade', models.IntegerField(choices=[(5, 'A+'), (4, 'A'), (3, 'B'), (2, 'C'), (1, 'D'), (0, '非公開')], default=5, verbose_name='成績')),
                ('overall', models.TextField(max_length=500, null=True, verbose_name='総評')),
                ('difficulty', models.TextField(max_length=100, null=True, verbose_name='難易度')),
                ('kadai', models.TextField(max_length=100, null=True, verbose_name='課題の量・質')),
                ('evaluation', models.TextField(max_length=100, null=True, verbose_name='評価の甘さ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('lecture', models.ForeignKey(default='GA13501', on_delete=django.db.models.deletion.CASCADE, to='review.subject')),
            ],
        ),
    ]
