# Generated by Django 3.2 on 2022-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_sender_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '5.0'), (4, '4.0'), (3, '3.0'), (2, '2.0'), (1, '1.0')], default=5, verbose_name='星'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sender_college',
            field=models.IntegerField(choices=[(1, '人文学類'), (2, '比較文化学類'), (3, '日本語・日本文化学類'), (4, '社会学類'), (5, '国際総合学類'), (6, '教育学類'), (7, '心理学類'), (8, '障害科学類'), (9, '生物学類'), (10, '生物資源学類'), (11, '地球学類'), (12, '数学類'), (13, '物理学類'), (14, '化学類'), (15, '応用理工学類'), (16, '工学システム学類'), (17, '社会工学類'), (18, '情報科学類'), (19, '情報メディア創成学類'), (20, '知識情報・図書館学類'), (21, '医学類'), (22, '看護学類'), (23, '医療科学類'), (24, '体育専門学群'), (25, '芸術専門学群'), (26, '総合学域群')], default=1, verbose_name='投稿者の所属学類'),
        ),
    ]
