# Generated by Django 3.2 on 2022-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220905_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='star5',
            field=models.IntegerField(default=1, verbose_name='星5'),
        ),
    ]
