# Generated by Django 3.2 on 2022-11-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20221120_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='', max_length=30, verbose_name='履修年次'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schools',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='学群等'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(default='', max_length=30, verbose_name='学期'),
        ),
    ]
