# Generated by Django 3.2.7 on 2022-11-25 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20221122_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('email', models.EmailField(max_length=40, verbose_name='メールアドレス')),
                ('message', models.TextField(max_length=500, verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
        ),
    ]
