# Generated by Django 3.2 on 2022-12-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='star4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='star5',
        ),
        migrations.AlterField(
            model_name='review',
            name='lecture',
            field=models.ForeignKey(default='GA13501', on_delete=django.db.models.deletion.CASCADE, related_name='related_reviews', to='review.subject'),
        ),
    ]
